<a href="https://colab.research.google.com/github/jeyakumar-nanc/MachineLearning/blob/main/Experiments_with_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note to grader:** Each question consists of parts, e.g. Q1(i), Q1(ii), etc. Each part must be graded  on a 0-4 scale, following the standard NJIT convention (A:4, B+: 3.5, B:3, C+: 2.5, C: 2, D:1, F:0). 
The total score must be re-scaled to 100 -- that should apply to all future assignments so that Canvas assigns the same weight on all assignments. 



In [ ]:
# Grader's area
import numpy as np
G = np.zeros([10,10])
maxScore = 0


# **Assignment 5**
<br>

<font>

In [ ]:
from IPython.display import Math
from IPython.display import Latex

import numpy as np
import os
import struct

from sklearn.metrics import classification_report,confusion_matrix
from sklearn.neural_network import MLPClassifier

----------------
----------------
----------------

## <font color='blue'> Question 0. MLP with scikit-learn: Explore outputs for the MNIST dataset </font>

The purpose of this question is to get some practice time with MLP classifiers. We will be using the the MNIST data set. 




In [ ]:
# Let's first load the MNIST data set. 

from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split


X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
y = y.astype(int)
X = ((X / 255.) - .5) * 2
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=10000, random_state=123, stratify=y)


In [ ]:
print(X_train.shape)
print(X_test.shape)

(60000, 784)
(10000, 784)


<br> **Q0-0**: This the classifier we built in class. Find a setting for *batch_size* and *max_iter*, so that the subsequent fit function **converges**. 





In [ ]:

mlp_mnist = MLPClassifier(verbose = True, hidden_layer_sizes=(50,), batch_size = 5, \
                          max_iter=50, solver='sgd', activation='logistic',\
                          learning_rate = 'constant', learning_rate_init = 0.001, random_state=1)



In [ ]:
mlp_mnist.fit(X_train,y_train)
#

Iteration 1, loss = 0.57329662
Iteration 2, loss = 0.28629488
Iteration 3, loss = 0.23811091
Iteration 4, loss = 0.20762641
Iteration 5, loss = 0.18553770
Iteration 6, loss = 0.16929318
Iteration 7, loss = 0.15646485
Iteration 8, loss = 0.14587802
Iteration 9, loss = 0.13694593
Iteration 10, loss = 0.12970190
Iteration 11, loss = 0.12320933
Iteration 12, loss = 0.11772963
Iteration 13, loss = 0.11267477
Iteration 14, loss = 0.10835127
Iteration 15, loss = 0.10453760
Iteration 16, loss = 0.10073217
Iteration 17, loss = 0.09726995
Iteration 18, loss = 0.09425700
Iteration 19, loss = 0.09151431
Iteration 20, loss = 0.08889736
Iteration 21, loss = 0.08643857
Iteration 22, loss = 0.08418907
Iteration 23, loss = 0.08249839
Iteration 24, loss = 0.08000014
Iteration 25, loss = 0.07834150
Iteration 26, loss = 0.07665299
Iteration 27, loss = 0.07502774
Iteration 28, loss = 0.07348437
Iteration 29, loss = 0.07206173
Iteration 30, loss = 0.07059095
Iteration 31, loss = 0.06904452
Iteration 32, los

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPClassifier(activation='logistic', batch_size=5, hidden_layer_sizes=(50,),
              max_iter=50, random_state=1, solver='sgd', verbose=True)

In [ ]:
predictions = mlp_mnist.predict(X_test)
probability_predictions = mlp_mnist.predict_proba(X_test)
print(len(probability_predictions))
probability_predictions[0]

10000


array([8.23495266e-01, 2.02135851e-03, 1.37493420e-03, 7.80373899e-05,
       2.35945456e-06, 1.54339750e-01, 1.60191247e-03, 1.77223350e-04,
       1.68747039e-02, 3.44547293e-05])

In [ ]:
print("Experimenting with 200 iterations and batch size of 20")

Experimenting with 200 iterations and batch size of 20


In [ ]:
### Your code here

mlp_mnist = MLPClassifier(verbose = True, hidden_layer_sizes=(50,), batch_size = 20, \
                          max_iter=200, solver='sgd', activation='logistic',\
                          learning_rate = 'constant', learning_rate_init = 0.001, random_state=1)

In [ ]:
mlp_mnist.fit(X_train,y_train)

Iteration 1, loss = 1.07589627
Iteration 2, loss = 0.46732489
Iteration 3, loss = 0.36872987
Iteration 4, loss = 0.32572183
Iteration 5, loss = 0.29882131
Iteration 6, loss = 0.27942237
Iteration 7, loss = 0.26370176
Iteration 8, loss = 0.25044798
Iteration 9, loss = 0.23905264
Iteration 10, loss = 0.22881868
Iteration 11, loss = 0.21980371
Iteration 12, loss = 0.21167679
Iteration 13, loss = 0.20430242
Iteration 14, loss = 0.19740963
Iteration 15, loss = 0.19112666
Iteration 16, loss = 0.18507471
Iteration 17, loss = 0.17973229
Iteration 18, loss = 0.17450256
Iteration 19, loss = 0.16987162
Iteration 20, loss = 0.16551028
Iteration 21, loss = 0.16128073
Iteration 22, loss = 0.15721502
Iteration 23, loss = 0.15368213
Iteration 24, loss = 0.14993207
Iteration 25, loss = 0.14685804
Iteration 26, loss = 0.14373177
Iteration 27, loss = 0.14073130
Iteration 28, loss = 0.13792801
Iteration 29, loss = 0.13528459
Iteration 30, loss = 0.13272948
Iteration 31, loss = 0.13010009
Iteration 32, los

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPClassifier(activation='logistic', batch_size=20, hidden_layer_sizes=(50,),
              random_state=1, solver='sgd', verbose=True)

In [ ]:
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[ 972    0    1    1    0    3    3    2    2    2]
 [   0 1112    3    4    1    1    0    2    1    1]
 [   3    4  976    4    1    1    3    3    3    1]
 [   3    1   11  980    1   13    1    4    5    1]
 [   0    1    3    0  951    0    7    1    2   10]
 [   5    1    1   12    3  865    2    1    7    5]
 [   6    2    4    1    2    7  954    0    6    0]
 [   3    2   10    4    4    0    0 1006    1   12]
 [   5    4    5    9    5    8    4    2  932    1]
 [   6    1    2    6   25    5    0   10    2  937]]
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       986
           1       0.99      0.99      0.99      1125
           2       0.96      0.98      0.97       999
           3       0.96      0.96      0.96      1020
           4       0.96      0.98      0.97       975
           5       0.96      0.96      0.96       902
           6       0.98      0.97      0.98       982
           7       0.98      0.97   

**Q0-1**: Write a short function that outputs the **second best** prediction for each point, i.e. the label which gets the second highest probability in the softmax output. 

In [ ]:
def second_best_pred():
  sb = np.argsort(probability_predictions)
  return(sb[:,-2]) #sort by desc and get the second best value

second_best = second_best_pred()

In [ ]:
second_best

array([5, 4, 0, ..., 3, 2, 3])

**Q0-2**: For each data point misclassified by the model, find if the second best prediction is actually the correct label. Calculate the percentage of missclassified points, that are correctly classified based on the second best prediction. 

In [ ]:
from sklearn.utils.extmath import stable_cumsum
### Your code here. Also give some comments about your findings
sb_correct = np.argwhere(y_test.to_list() == second_best) #get the correctly classfied based on second predictions
misclassify_percent = len(sb_correct)/len(y_test)*100
print(f"Misclassified percent - {misclassify_percent}%")



Misclassified percent - 2.1%


**Q0-3**: From a human point of view, we can perhaps see a frequent similarity between handritten digits 3 and 5 (i.e. sometimes we have to pay closer attention to figure out what the true written digit is). We may want to ask if the MLP also detects digit similarities.    
<br>
 Consider then the subset $X_i$ of data points that have label $i$ (e.g. all data points with label 5). For each label $j\neq i$, report the frequency by which label $j$ (e.g. label 3) shows up as second best prediction for points in $X_i$. 
<br>
<br> 
***Further Clarification***: Suppose we have 100 data points with label i=5. Let's say that for 28 of these 100 points, the second predicted label is j=3. Then, the frequency of j=3 as second-best prediction to i=5 is 28%.  We want to compute that frequency for every i and j.  
<br>  
 Give your code and comment on your findings 

In [ ]:
### Your code here. Also give some comments about your findings

def freq_second_best(second_best, label, similar_label):
  tmp = np.argwhere(predictions == label) #get original predictions for given label
  sec_best_pred = second_best[tmp] #second best for the label
  
  #print(total)
  counts = dict()
  pred_list = list(sec_best_pred[:,0])
  for i in range(len(pred_list)):
    counts[pred_list[i]] = counts.get(pred_list[i], 0) + 1 #count the second best predictions

  print(counts)
  print(counts.get(similar_label))
  print(f"Frequency of j={similar_label} as second best to i={label} is Percent - {counts.get(similar_label)/len(pred_list)*100}%")



print(f"For label 5, frequency of second best")
freq_second_best(second_best,5,3)


print(f"\nFor label 3, frequency of second best")
freq_second_best(second_best,3,5)





For label 5, frequency of second best
{1: 58, 8: 178, 0: 78, 9: 105, 3: 350, 4: 36, 6: 71, 2: 19, 7: 8}
350
Frequency of j=3 as second best to i=5 is Percent - 38.759689922480625%

For label 3, frequency of second best
{5: 402, 1: 107, 9: 197, 2: 103, 7: 90, 8: 103, 0: 9, 6: 3, 4: 7}
402
Frequency of j=5 as second best to i=3 is Percent - 39.373163565132224%


In [ ]:
# For grader use only

# insert grade here
# G[0,0] =   
# G[0,1] = 
# G[0,2] =
# G[0,3] = 


maxScore = maxScore + 16


------------------------------
------------------------------
------------------------------

## <font color='blue'>Question 1: Working with warm start for focused training



In [ ]:
### Your code here. Also give some comments about your findings
#for 100 epochs

mlp_mnist_ws = MLPClassifier(verbose = False, hidden_layer_sizes=(50,), batch_size = 20, warm_start = True, \
                          max_iter=1000, solver='sgd', activation='logistic',\
                          learning_rate = 'constant', learning_rate_init = 0.001, random_state=1)


**Q1-0**. MLP classifiers in scikit-learn have an option for so-called 'warm start'. Do a bit of research to find out what it is. Then:

Give an example of warm start. Specifically
train the network for $k$ epochs, and then using warm start
continue the training for another $k$ epochs (4 points).
Here $k$ is a parameter of your choice.  







---


When warm-start set to True, it reuses the solution of the previous call to fit as initialization, and as a result it runs faster than the previous run.

In [ ]:
mlp_mnist_ws.fit(X_train,y_train)

MLPClassifier(activation='logistic', batch_size=20, hidden_layer_sizes=(50,),
              max_iter=1000, random_state=1, solver='sgd', warm_start=True)

In [ ]:
prev_loss = mlp_mnist_ws.loss_
prev_coefs = mlp_mnist_ws.coefs_
prev_intercepts = mlp_mnist_ws.intercepts_

In [ ]:
mlp_mnist_ws.fit(X_train,y_train)

MLPClassifier(activation='logistic', batch_size=20, hidden_layer_sizes=(50,),
              max_iter=1000, random_state=1, solver='sgd', warm_start=True)

In [ ]:
print(prev_loss==mlp_mnist_ws.loss_)
print(prev_coefs==mlp_mnist_ws.coefs_)
print(prev_intercepts==mlp_mnist_ws.intercepts_)

False
True
True



The training set usally remains the same after a warm start. Here, we will use a very similar bit not identical dataset after the warm start:
<br>
<br>
**Q1-1**. Randomly divide the MNIST dataset into three part: train1 (50000), train2(10000), test (10000). Make sure that all number classes are presented in both train1, and train2. [4 points]


In [ ]:
### Your code here. Also give some comments about your findings

X_train1, X_train2, y_train1, y_train2 = train_test_split(
    X, y, test_size=0.15, random_state=123, stratify=y) #using test train split size randomly dividing the data train1 and tarin2 are more or less closer to the requirement

In [ ]:
print(X_train1.shape)
print(X_train2.shape)
#print(X_test.shape)

(59500, 784)
(10500, 784)


**Q1-2**. Use warm start and train your model using the train1 dataset for $2k$ epochs. Then, using warm start, continute the training with train2 dataset for another $2k$ epochs. [4 points]
<br>
<br>
Here $k$ is the same parameter you used above. Notice that each point
is considered $2k$ times in this training, exactly as in part 0. 
<br>
<br>
In effect this process of training tries spend more time learning half of the training set, and then moves to the second part of the training set to spend equal time. 


In [ ]:
### Your code here. Also give some comments about your findings

mlp_mnist_ws = MLPClassifier(verbose = False, hidden_layer_sizes=(50,), batch_size = 20, warm_start = True, \
                          max_iter=2000, solver='sgd', activation='logistic',\
                          learning_rate = 'constant', learning_rate_init = 0.001, random_state=1)



In [ ]:
mlp_mnist_ws.fit(X_train1,y_train1)

MLPClassifier(activation='logistic', batch_size=20, hidden_layer_sizes=(50,),
              max_iter=2000, random_state=1, solver='sgd', warm_start=True)

In [ ]:
prev_loss = mlp_mnist_ws.loss_
prev_coefs = mlp_mnist_ws.coefs_
prev_intercepts = mlp_mnist_ws.intercepts_

In [ ]:
mlp_mnist_ws.fit(X_train2,y_train2)

MLPClassifier(activation='logistic', batch_size=20, hidden_layer_sizes=(50,),
              max_iter=2000, random_state=1, solver='sgd', warm_start=True)

In [ ]:
print(prev_loss==mlp_mnist_ws.loss_)
print(prev_coefs==mlp_mnist_ws.coefs_)
print(prev_intercepts==mlp_mnist_ws.intercepts_)

False
True
True


**Q1-3**. Which of the two above strategies
works better? (Q1-0 or Q1-2). Feel free to experiment and report your findings.

Q1-0 took 34 mins 50s for 1000 iterations where as
Q1-2 took 32mins for 2000 iterations. 
Q1-2 is works better, execution time for 1000 iterations for randonly divided is half of the original execution.

In [ ]:
# For grader use only

# insert grade here
# G[1,0] =   
# G[1,1] = 
# G[1,2] =
# G[1,3] = 


maxScore = maxScore + 16


--------------------------
--------------------------
--------------------------

##  <font color='blue'> Q2. How Powerful are Neural Networks? 

There is a lot of hype around Neural Networks, and their ability to solver problems. This is of course justified, but we should always be aware of their limitations. 


Recall that every row in the matrix $X$  above comes from an image. Every entry of a row corresponds to a (grayscale) pixel. In particular, the first colum of $X$ contains the grayscale values of the first pixels of the images in the data set. 
<br>
<br>
We will now 'hide' the label of the image, inside the image itself. 
Here is one way to do that: Replace the top-left pixel of the image (which is a value from 0 to 255) with the label for that image. For example, if the image
contains number 3, then the first pixel of the image will now be set to 3. (In fact, let's set this to 3/255 because we already divided all pixel values by 255).

**Q2-0.** Create a new dataset $X1$, where each row is the same as the corresponding row of $X$, except in the first column, which contains the label of the corresponding image, divided by 255. Then split
the set $X1$ into a training set and a test set, as we did with $X$. 




In [ ]:
# your code here
X1 = X

X1.iloc[:,0]=y
#print(X1.iloc[:,0])
X1.iloc[:,0]=round((X1.iloc[:,0]/255.),2)
print(X1.iloc[:,0])


X1_train, X1_test, y1_train, y1_test = train_test_split(
    X1, y, test_size=10000, random_state=123, stratify=y)
print(X1_train.shape)
print(y1_train.shape)

0        0.02
1        0.00
2        0.02
3        0.00
4        0.04
         ... 
69995    0.01
69996    0.01
69997    0.02
69998    0.02
69999    0.02
Name: pixel1, Length: 70000, dtype: float64
(60000, 784)
(60000,)


**Q2-1.** With the label of the image 'planted' in the image itself, a Neural Network can achieve accuracy 100%. This is because all the weights connecting to pixels $2...28^2$ can be set to 0, and so effectively the only feature that will be taken into account is the first pixel. The question is whether an MLP can indeed 'discover' this weighting via training.
<br>
<br>
Use an MLP classifier  with one hidden layer of any size you want. Train it on $X'$ and report the accuracy. Does it reach 100\%? Is the accuracy better relative to training with the original input $X$? 




In [ ]:
mlp_mnist_new = MLPClassifier(verbose = True, hidden_layer_sizes=(50,), batch_size = 20, \
                          max_iter=200, solver='sgd', activation='logistic',\
                          learning_rate = 'constant', learning_rate_init = 0.001, random_state=1)
mlp_mnist_new.fit(X1_train,y1_train)
#mlp_mnist_new.fit(X1_train.values.reshape(-1,1),y1_train.values.reshape(-1,1))

Iteration 1, loss = 1.07596646
Iteration 2, loss = 0.46730642
Iteration 3, loss = 0.36870501
Iteration 4, loss = 0.32569851
Iteration 5, loss = 0.29880066
Iteration 6, loss = 0.27940394
Iteration 7, loss = 0.26368502
Iteration 8, loss = 0.25043111
Iteration 9, loss = 0.23903567
Iteration 10, loss = 0.22880048
Iteration 11, loss = 0.21978464
Iteration 12, loss = 0.21165585
Iteration 13, loss = 0.20427933
Iteration 14, loss = 0.19738352
Iteration 15, loss = 0.19109622
Iteration 16, loss = 0.18504141
Iteration 17, loss = 0.17969305
Iteration 18, loss = 0.17445775
Iteration 19, loss = 0.16982248
Iteration 20, loss = 0.16545608
Iteration 21, loss = 0.16121932
Iteration 22, loss = 0.15714829
Iteration 23, loss = 0.15360873
Iteration 24, loss = 0.14985267
Iteration 25, loss = 0.14677403
Iteration 26, loss = 0.14364359
Iteration 27, loss = 0.14063741
Iteration 28, loss = 0.13782830
Iteration 29, loss = 0.13518066
Iteration 30, loss = 0.13262195
Iteration 31, loss = 0.12999251
Iteration 32, los

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPClassifier(activation='logistic', batch_size=20, hidden_layer_sizes=(50,),
              random_state=1, solver='sgd', verbose=True)

In [ ]:
#predictions_new = mlp_mnist_new.predict(X1_test.values.reshape(-1,1))
predictions_new = mlp_mnist_new.predict(X1_test)
probability_predictions_new = mlp_mnist_new.predict_proba(X1_test)
print(confusion_matrix(y1_test,predictions_new))
print(classification_report(y1_test,predictions_new))

[[ 971    0    2    0    0    0    5    1    2    5]
 [   0 1113    4    0    1    0    0    3    2    2]
 [   3    3  975    3    1    2    2    4    5    1]
 [   4    1   13  971    0   10    1    6    9    5]
 [   1    1    4    0  936    0    8    4    3   18]
 [   5    1    1   13    2  861    3    1    7    8]
 [   7    2    2    1    1    5  957    0    7    0]
 [   3    3    7    3    3    1    0 1009    2   11]
 [   7    3    4    6    3    4    4    1  943    0]
 [   6    1    1    6   18    2    0   11    5  944]]
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       986
           1       0.99      0.99      0.99      1125
           2       0.96      0.98      0.97       999
           3       0.97      0.95      0.96      1020
           4       0.97      0.96      0.96       975
           5       0.97      0.95      0.96       902
           6       0.98      0.97      0.98       982
           7       0.97      0.97   

Accuary reached 97% and it more or less same as the original dataset

In [ ]:
# For grader use only

# insert grade here
# G[2,0] =   
# G[2,1] = 
# G[2,2] =


maxScore = maxScore + 12


In [ ]:
# for grader use

# Total Grade Calculation
rawScore = np.sum(G)
score = rawScore*100/maxScore